### ISSUE TITLE
64-bit support?

### ISSUE THREAD

**Issue by iMaciah** [adrianopaladini/statusbar#1]
Any chance to update this module to 64-bit?

Regards

**Comment by adrianopaladini** [comment]
In this weekend i'll upgrade all my modules!

**Comment by adrianopaladini** [comment]
Hi, in this weekend i'll update all my modules.

**Comment by de1mat** [comment]
How is this going? Looking to experiment with this module but won't work in a new project due to lack of 64-bit support...

**Comment by darkhorse2013** [comment]
Hi, I need the 64 bit module too thanks

**Comment by pilosof** [comment]
any news :) tnx !!

**Comment by darkhorse2013** [comment]
yep really need the status bar upgraded with 64 bit support as well.

**Comment by fleonard** [comment]
Looking forward to 64-bit support.
I'm new to titanium but looks a must have module!

**Comment by iMaciah** [comment]
Any news ??

**Comment by adrianopaladini** [comment]
New version in 64-bit released
