### ISSUE TITLE
Script Error Couldn't find module: com.apaladini.statusbar for architecture: x86_64

### ISSUE THREAD

**Issue by deckameron** [adrianopaladini/statusbar#2]
Hi Adriano,

Thank you for this module.
I downloaded the latest version, 2.0, but unfortunately I still see this error while compiling with SDK 3.5.1.

**Comment by adrianopaladini** [comment]
This is a very strange, you could send me all the log?

**Comment by adrianopaladini** [comment]
This: "[ERROR] :  Script Error Couldn't find module: com.apaladini.statusbar for architecture: x86_64" is usually displayed if the module is not added to the list of modules in tiapp.xml

**Comment by deckameron** [comment]
Thank you for your fast response!
I had already checked if the module was added to tiapp.xml but still no luck, so I cleaned the build and closed Titanium Studio and tried again and it worked.... It is so weird.
Thanks again.
